### ISSUE TITLE
Application Crash While I am running it on Xcode 7

### ISSUE THREAD

**Issue by faizanrefai** [as-cii/PdfReportKit#25]
I had verify this code is not running now,

I put Try Catch and I receive this Log,

2016-05-24 16:31:02.710 PdfReportKit[9945:463309] Class : PRKGenerator :::  Method : -[PRKGenerator createPage:] -[__NSCFString replaceOccurrencesOfString:withString:options:range:]: nil argument

The code:

```
        [wellFormedHeader replaceOccurrencesOfString:[renderedTags objectForKey:@"pageContent"] withString:@"" options:NSLiteralSearch range:NSMakeRange(0, wellFormedHeader.length)];
```

in PRKGenerator never call datasource methods, and the object renderedTags is always zero key value pair.

Please fix this, or Guide me I will change it and send you updated code here

**Comment by as-cii** [comment]
Hey @faizanrefai,

I am sorry but I don't maintain this library anymore. Please, feel free to fork it and I'll be happy to mention your fork in this repository's `README.md` if it is actively developed and new features/bug fixes get submitted to it.

Thanks! Closing this for now. 🙇
